title: <p align="center"> Allena Venkata Sai Abhishek</p>
logo: /assets/img/pp.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/allena-venkata-sai-abhishek-381937156/">LinkedIn</a> |
  <a href="https://github.com/avs-abhishek123">GitHub</a>
  
  <br> 
  <BR>
  I'm working on Data Science, Machine learning & Computer Vision.
  Also handing the Big Data from real-time Ad call data.
  Worked with Research at Big Data Analytics team.
  <br>
  <br>
  </p>



theme: jekyll-theme-minimal
show_downloads: true
google_analytics:

